### ISSUE TITLE
how to use this autoscontro?

### ISSUE THREAD

**Issue by woshikangfei** [mpatander/autoscontro#1]
hello, i find you opensource, i have a mkz car,but i can not control the car steering wheel，is your source code can do this ?

**Comment by mpatander** [comment]
Hi,
to control the car you need actuators, CAN control boxes (such those provided by dataspeed inc) and access to the CAN bus.
Currently the library is still under development and testing, but it is planned to support throttle, braking as well as steering control. Maybe we will tag/branch when we will have a stable version - but it's too early for that.

Best regards,
Marco Patander

**Comment by mpatander** [comment]
Tested on car: working (also the steering).
Refer to current master branch.
